# Generated by Django 5.1.4 on 2025-05-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopsy', '0004_user_is_active_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
    ]
