# Generated by Django 5.1.4 on 2025-05-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopsy', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
